id: P489CC66C
initial_creation_type: ocr
source_metadata:
  volumes:
    9717586b164e4cc1833ecfcbe6769307:
      base_file: v037.txt
      image_group_id: I1PD95882
      title: འཕགས་པ་འཇམ་པའི་དབྱངས་ཀྱི་བསྟོད་པ།
      total_pages: 1379
      volume_number: 37
