id: D8C55E568
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-11T09:50:18+00:00'
last_modified: '2022-05-26T12:06:40.184186+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    973a:
      image_group_id: I1PD95882
      title: འཕགས་པ་འཇམ་པའི་དབྱངས་ཀྱི་བསྟོད་པ།
      total_pages: 1379
      order: 37
      base_file: 973a.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
